### ISSUE TITLE
Add support to specify user Groups in icinga Notifications

### ISSUE THREAD

**Issue by sgruber94** [T-Systems-MMS/ansible-collection-icinga-director#111]
Background:  
I want to specify user groups to add users into group and not adjusting notification rules
We have more flexibility to (add/remove/update) users.

Actual:
- Only Users could be add into the Notification.

requirements:
-  user groups need to be created first

**Comment by rndmh3ro** [comment]
Yes, that should be added! Do you want to give it a try?

**Comment by sgruber94** [comment]
yeah sure, i can give a try :)
