### ISSUE TITLE
Add support for Environment Vars in Check Command

### ISSUE THREAD

**Issue by loquilloll** [T-Systems-MMS/ansible-collection-icinga-director#137]
As specified in the [Icinga docs](https://icinga.com/docs/icinga-2/latest/doc/03-monitoring-basics/#environment-variables).

```
object CheckCommand "mysql" {
  command = [ PluginDir + "/check_mysql" ]

  arguments = {
    "-H" = "$mysql_address$"
    "-d" = "$mysql_database$"
  }

  vars.mysql_address = "$address$"
  vars.mysql_database = "icinga"
  vars.mysql_user = "icinga_check"
  vars.mysql_pass = "password"

  env.MYSQLUSER = "$mysql_user$"
  env.MYSQLPASS = "$mysql_pass$"
}
```

**Comment by rndmh3ro** [comment]
How do you actually define these in the director? I couldn't find a way to do it neither in the frontend nor via the API.

**Comment by rndmh3ro** [comment]
Closing this because of a lack of response. Feel free to open an new issue with additional details.
