### ISSUE TITLE
module not working with director v1.9.0

### ISSUE THREAD

**Issue by axxeo** [T-Systems-MMS/ansible-collection-icinga-director#160]
Hello,
we upgraded director to v1.9.0 and since then the module produces the folllowing error on the second playbook run:

```
failed: [icinga2-master1.localdomain] (item={'name': 'director-generic-service', 'enable_active_checks': True, 'enable_event_handler': True, 'enable_flapping': True, 'enable_notifications': True, 'eanble_passive_checks': True, 'enable_perfdata': True, 'use_agent': True, 'volatile': False}) => {"ansible_loop_var": "item", "changed": false, "item": {"eanble_passive_checks": true, "enable_active_checks": true, "enable_event_handler": true, "enable_flapping": true, "enable_notifications": true, "enable_perfdata": true, "name": "director-generic-service", "use_agent": true, "volatile": false}, "msg": "bad return code while creating: 422. Error message: Trying to recreate icinga_service (\"{\"object_name\":\"director-generic-service\"}\")"}
```

we think it is an problem with the new feature:
FEATURE: UUIDs have been implemented for most Icinga objects, more to come

director v1.8.1 still works.

**Comment by rndmh3ro** [comment]
The collection is untested with v1.9.0. Thanks for creating the bug-report, well have to take a look.

**Comment by rndmh3ro** [comment]
I investigated and the issue is with the Director.
See this issue for more details: https://github.com/Icinga/icingaweb2-module-director/issues/2487
