### ISSUE TITLE
wrong parameter force_basic_auth mentioned in README.md

### ISSUE THREAD

**Issue by sjedlick** [T-Systems-MMS/ansible-collection-icinga-director#201]
### Description

In the README.md section "Troubleshooting" (https://github.com/T-Systems-MMS/ansible-collection-icinga-director#troubleshooting) it is mentioned that using "force_basic_auth: true" fixes the problem with the Icinga Director probably sitting behind a Basic Authentication prompt.
In my opinion, "icinga_force_basic_auth: true" must be used as defined in the ansible_icinga tasks.

**Comment by rndmh3ro** [comment]
The parameter for the modules is correctly called `force_basic_auth`.
Only in the included role is it called `icinga_force_basic_auth` to avoid having the same name.

Feel free to create a PR to add this to the documentation!
