### ISSUE TITLE
  module_defaults not working for deploy modules

### ISSUE THREAD

**Issue by MarcusCaepio** [T-Systems-MMS/ansible-collection-icinga-director#212]
Good morning all,
I have set the module_defaults like described in the docs and it is working for e.g. creating templates. But unfortunately, the deploy and deploy_info module throw the error "url is missing". So it seems the module defaults are not working there.

Cheers,
Marcus

**Comment by rndmh3ro** [comment]
You're right, thanks for spotting!

The modules need to be added here: https://github.com/T-Systems-MMS/ansible-collection-icinga-director/blob/master/meta/runtime.yml

And a test is needed here: https://github.com/T-Systems-MMS/ansible-collection-icinga-director/blob/master/tests/integration/targets/defaults_test/defaults_test.yml

Additionally we have to document what has to be done if a new module is added to the collection.

Do you want to tackle any of these?

**Comment by rndmh3ro** [comment]
Fixed by #214
