### ISSUE TITLE
Modules always sets values in quotes

### ISSUE THREAD

**Issue by MarcusCaepio** [T-Systems-MMS/ansible-collection-icinga-director#213]
Good Morning again,

Is there any way to prevent the values from always being set in quotation marks in the module? I am trying to reference a host variable in a service template like in this DSL snippet:
```
template Service "generic-service" {
  icon_image = host.icon_image
  [...]
```
But the following tasks creates quotation marks automatically:
```
  t_systems_mms.icinga_director.icinga_service_template:
    icon_image: host.icon_image
    [....]
```
Results in DSL Snip
```
template Service "generic-service" {
  icon_image = "host.icon_image"
  [...]
```
Imho, it would be nice, that we have to use quotation marks in the modules, when we also need them in the config and if we want to reference to other objects ( or e.g. constants) we just can leave them out.

Cheers,
Marcus

**Comment by rndmh3ro** [comment]
Normally the modules don't set any quotes explicitly, so I guess Python or the director itself does it.

I'll have to check. But I'll probably not get to this in this week.

**Comment by MarcusCaepio** [comment]
Thanks a lot. I am currently running the latest director version ( 1.10.2 )

**Comment by rndmh3ro** [comment]
>  So I guess, the director does not support the usage of constants ( what imho again would be a k.o. criteria...). Would be nice if you could verify this :)

I just tested this and you're right. 
This seems to be the same problem: https://github.com/Icinga/icingaweb2-module-director/issues/1075

So I'm closing this as there's nothing we can do here.
