### ISSUE TITLE
No IPv6-Address Variable for Hosts

### ISSUE THREAD

**Issue by chris2k20** [T-Systems-MMS/ansible-collection-icinga-director#36]
Not possible to set a IPv6 Address for a Host:

![image](https://user-images.githubusercontent.com/49652410/89127297-bc9d0980-d4ec-11ea-8bd6-e367ba192ac9.png)

Error message: 
```
fatal: [localhost]: FAILED! => changed=false 
  msg: 'Unsupported parameters for (icinga_host) module: address6 Supported parameters include: address, check_command, client_cert, client_key, disabled, display_name, force_basic_auth, groups, imports, object_name, state, url, url_password, url_username, use_proxy, validate_certs, vars, zone'
```
Is it possible to implement this variable for a host. Thank you for this nice project! 💯

**Comment by schurzi** [comment]
this is fixed now in master and will be soon published in 1.4.0
