### ISSUE TITLE
Unsupported parameter "Notes" for icinga_host

### ISSUE THREAD

**Issue by opencommits** [T-Systems-MMS/ansible-collection-icinga-director#50]
The following field is not configurable in the current version of the ansible role: 

![grafik](https://user-images.githubusercontent.com/54305643/96229639-845b8200-0f97-11eb-9078-f6d69acdef21.png)

I've got the following error code: 

`FAILED! => {"changed": false, "msg": "Unsupported parameters for (t_systems_mms.icinga_director.icinga_host) module: notes Supported parameters include: address, address6, check_command, client_cert, client_key, disabled, display_name, force_basic_auth, groups, imports, object_name, state, url, url_password, url_username, use_proxy, validate_certs, vars, zone"}`

Thx for the great job on this project! 👍

**Comment by rndmh3ro** [comment]
Yeah, notes are not supported yet. We should definetly add support for them.

**Comment by rndmh3ro** [comment]
I just noticed that we already have support in the service_apply module for notes, see here:
* https://github.com/T-Systems-MMS/ansible-collection-icinga-director/blob/master/plugins/modules/icinga_service_apply.py#L135-L146
* https://github.com/T-Systems-MMS/ansible-collection-icinga-director/blob/master/plugins/modules/icinga_service_apply.py#L226-L227
* https://github.com/T-Systems-MMS/ansible-collection-icinga-director/blob/master/plugins/modules/icinga_service_apply.py#L244-L245

So for anyone wanting to contribute: you'd just have to check where notes are supported and then add the corresponding code.

**Comment by rndmh3ro** [comment]
Notes should be available in https://github.com/T-Systems-MMS/ansible-collection-icinga-director/releases/tag/1.8.0 now!
