### ISSUE TITLE
Remove unwanted files from release-tarball

### ISSUE THREAD

**Issue by rndmh3ro** [T-Systems-MMS/ansible-collection-icinga-director#58]
The release tar-ball contains file that do not need to be inside the installed collection. That contains tests, linting, coverage, github action workflows, the test-generation scripts, requirements-files.

I propose that we add the following files to the build-ignore list:
```
-rw-r----- 1 root root    70 Oct 20 08:08 codecov.yml
drwxr-x--- 1 root root  4096 Sep 30 19:43 .github/
drwxr-x--- 1 root root  4096 Oct 22 09:13 hacking/
-rw-r----- 1 root root     8 Sep 30 19:43 requirements.txt
-rw-r----- 1 root root    62 Sep 30 19:43 test-requirements.txt
drwxr-x--- 1 root root  4096 Oct 22 09:49 tests/
drwxr-x--- 1 root root  4096 Oct 20 10:43 .tox/
-rw-r----- 1 root root   878 Sep 30 19:43 tox.ini
-rw-r----- 1 root root   298 Oct 22 09:13 .yamllint
```

**Comment by xFuture603** [comment]
Important side note: "This feature is only supported when running ansible-galaxy collection build with Ansible 2.10 or newer."

source: https://docs.ansible.com/ansible/latest/dev_guide/developing_collections.html
