### ISSUE TITLE
icinga_commands with "imports" not working

### ISSUE THREAD

**Issue by tex443** [T-Systems-MMS/ansible-collection-icinga-director#63]
When I try to create a command and use imports it throws an error:
_bad return code while creating: 404. Error message: Failed to load icinga_command \"plugin-notification-command\""}_
Imports doesn't seem to be necessary because the import is selected automatically depending on the command_type.
Maybe only the example needs to be modified?

**Comment by rndmh3ro** [comment]
Yes, `imports` is an optional parameter, as described in the docs.

> Imports doesn't seem to be necessary because the import is selected automatically depending on the command_type.

Maybe in the web-UI of the director? When using the API there is no automatic select.

> Maybe only the example needs to be modified?

Which example do you mean? I don't see an example where we use `plugin-notification-command`.
Can you share your playbook, please?

**Comment by tex443** [comment]
[https://github.com/T-Systems-MMS/ansible-collection-icinga-director/blob/master/examples/icinga_command.yml](url)
Line 47

My Code:


```- name: change centreon plugins
  icinga_command:
    state: present
    force_basic_auth: yes
    url: "{{ icinga_url }}"
    url_username: "{{ icinga_user }}"
    url_password: "{{ icinga_pass }}"
    arguments:
      '--authpassphrase':
        value: $snmpv3_priv_key$
      '--authprotocol':
        value: $snmpv3_auth_protocol$
      '--critical':
        value: $centreon_critical$
      '--filter':
        value: $centreon_filter$
      '--hostname':
        value: $snmp_address$
      '--maxrepetitions':
        value: $centreon_maxrepetitions$
      '--mode':
        value: $centreon_mode$
      '--state':
        value: $centreon_state$
      '--service':
        value: $snmp_service_name$
      '--plugin':
        value: $centreon_plugin$
      '--privpassphrase':
        value: $snmpv3_auth_key$
      '--privprotocol':
        value: $snmpv3_priv_protocol$
      '--snmp-community':
        value: $snmp_community$
      '--snmp-timeout':
        value: $snmp_timeout$
      '--snmp-username':
        value: $snmpv3_user$
      '--snmp-version':
        value: $snmp_version$
      '--subsetleef':
        value: $centreon_subsetleef$
      '--verbose':
        set_if: $centreon_verbose$
      '--warning':
        value: $centreon_warning$
      '--regexp':
        set_if: $centreon_regexp$
    command: "/opt/centreon-plugins/centreon_plugins.pl"
    command_type: "PluginCheck"
    disabled: false
    object_name: centreon-plugins
    # imports: "plugin-check-command"
    timeout: "1m"
    vars:
      centreon_maxrepetitions: 20
      centreon_subsetleef: 20
      centreon_verbose: false
      snmp_address: $address$
      snmp_timeout: 60
      snmp_version: '2'
      snmpv3_auth_key: authkey
      snmpv3_priv_key: privkey
      snmpv3_user: user
  notify: deploy config
  run_once: True
  tags: centreon
```

It works only with commented out "imports".
Bit in Icinga it is created:
(Line 2)

```
object CheckCommand "centreon-plugins" { 
import "plugin-check-command" 
command = [ "/opt/centreon-plugins/centreon_plugins.pl" ] 
arguments += { 
    "--authpassphrase" = "$snmpv3_priv_key$" 
    "--authprotocol" = "$snmpv3_auth_protocol$" 
    "--critical" = "$centreon_critical$" 
    "--filter" = "$centreon_filter$" 
    "--filter-perfdata" = { 
        set_if = "$forti_vpn_perfdata$" 
    } 
    "--filter-vdomain" = "$forti_vpn_filter_vdom$" 
    "--filter-vpn" = "$forti_vpn_filter_vpn$" 
    "--hostname" = "$snmp_address$" 
    "--maxrepetitions" = "$centreon_maxrepetitions$" 
    "--mode" = "$centreon_mode$" 
    "--plugin" = "$centreon_plugin$" 
    "--privpassphrase" = "$snmpv3_auth_key$" 
    "--privprotocol" = "$snmpv3_priv_protocol$" 
    "--snmp-community" = "$snmp_community$" 
    "--snmp-timeout" = "$snmp_timeout$" 
    "--snmp-username" = "$snmpv3_user$" 
    "--snmp-version" = "$snmp_version$" 
    "--subsetleef" = "$centreon_subsetleef$" 
    "--verbose" = { 
        set_if = "$centreon_verbose$" 
    } 
    "--warning" = "$centreon_warning$" 
} 
vars.centreon_maxrepetitions = 20 
vars.centreon_subsetleef = 20 
vars.centreon_verbose = false 
vars.forti_vpn_perfdata = false 
vars.snmp_address = "$address$" 
vars.snmp_timeout = 60 
vars.snmp_version = "2" 
vars.snmpv3_auth_key = "authkey" 
vars.snmpv3_priv_key = "privkey" 
vars.snmpv3_user = "user" 
}
```

**Comment by rndmh3ro** [comment]
Thanks, though in the example there is an import for `centreon-plugins-template`. 

The reason for your error is that the command_template `plugin-check-command` that you icinga_command references does not exist in your installation. That's why it 404s. So that's working as expected. You have to create it before you can use it.

@schurzi, what do you think? Should we rely on the API to produce a 404 error if an import is missing or should we provide the functionality that checks if an import exists before creating an object with an import?

As to modify the example: 
Maybe we could do this, however we also use these examples in our automatic tests. There the command_template `centreon-plugins-template` gets created before the icinga_command is run. See here: https://github.com/T-Systems-MMS/ansible-collection-icinga-director/blob/master/tests/integration/targets/icinga/roles/icinga/tasks/main.yml#L4-L5

So if we change the example to a minimal working example, we'd lose the connection between the command and command_template. What we can do is provide another example without an import 4r4r4r4r4rer

**Comment by tex443** [comment]
In the example file is already a second (minimalistic) Task:

```
- name: create command
  icinga_command:
    state: present
    url: "{{ icinga_url }}"
    url_username: "{{ icinga_user }}"
    url_password: "{{ icinga_pass }}"
    command: "/opt/centreon-plugins/centreon_plugins_2.pl"
    object_name: centreon-plugins_2
```

**Comment by tex443** [comment]
But the big example is important to see what is possible.
Maybe it could be modified to work with standard components?

**Comment by rndmh3ro** [comment]
> Maybe it could be modified to work with standard components?

There are no default command templates in icinga defined.

I don't really see a way then other then reading the documentation and see what's possible with the modules. I'm open to ideas though. :)

**Comment by schurzi** [comment]
> @schurzi, what do you think? Should we rely on the API to produce a 404 error if an import is missing or should we provide the functionality that checks if an import exists before creating an object with an import?

I think relying on the API is fine. Generating custom errors and checks in our collection will surely bload our code and might tun out a mess to maintain, since behaviour cloud change.

What might be a good idea: can we pass more of the API error message to the output? Maybe that would clarify the error for the user.

**Comment by rndmh3ro** [comment]
> Generating custom errors and checks in our collection will surely bload our code and might tun out a mess to maintain, since behaviour cloud change.

Probably, yes. I don't even know all relations we'd have to check, apart from the imports. Seems not feasible.

> What might be a good idea: can we pass more of the API error message to the output? Maybe that would clarify the error for the user.

I just checked: the error message is all the API provides.

**Comment by schurzi** [comment]
Maybe it'S best, if we open an issue with https://github.com/Icinga/icingaweb2-module-director to make the error more descriptive?

**Comment by rndmh3ro** [comment]
I created an upstream issue: https://github.com/Icinga/icingaweb2-module-director/issues/2224

Since we cannot do any more in the collection, I'll close this ticket. @tex443 if you have an idea what to improve, feel free to reopen the ticket.
